**Numpy In Python**
-

In [88]:
import numpy as np

In [89]:
arr1=np.ndarray(range(1,10))
arr1

array([[[[[[[[[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              ...,
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.]],

             ...,

             [[0., 0., 0., ..., 0., 0., 0.],
              [0., 0., 0., ..., 0., 0., 0.],
              [0.,

In [90]:
tuple1=[1,2,3,4,52.20]

In [91]:
arr1=np.array(tuple1)
arr1

array([ 1. ,  2. ,  3. ,  4. , 52.2])

In [92]:
print(arr1)

[ 1.   2.   3.   4.  52.2]


create a Zero Value array

In [93]:
arr2=np.zeros([2,3])
arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
arr2=np.ones([3,3])
arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Arange & Linespace

In [95]:
arr1=np.arange(0,10,2)
arr1

array([0, 2, 4, 6, 8])

In [96]:
arr1=np.linspace(0,1,10)
arr1

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

Randomm Arrray

In [97]:
arr1=np.random.rand(2,3)
arr1

array([[0.48799302, 0.73102984, 0.52396918],
       [0.76542158, 0.66795536, 0.41803117]])

Random Number 

In [98]:
arr1=np.random.randint(1,100)
arr1

84

Accessing Milti Dimensional Array

In [116]:
arr1=np.array([1,2,3,4],ndmin=4)
arr1

array([[[[1, 2, 3, 4]]]])

In [121]:
arr1.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [122]:
arr1.shape

(2, 2)

In [124]:
arr2=np.array([1,21,2,'sasa'],ndmin=4)

In [125]:
arr2

array([[[['1', '21', '2', 'sasa']]]], dtype='<U11')

In [127]:
arr2.reshape(2,2)

array([['1', '21'],
       ['2', 'sasa']], dtype='<U11')

In [128]:
arr2.dtype

dtype('<U11')

In [144]:
arr2=np.array([[1,2,3,10],[4,5,6,11],[7,8,9,12]])


In [145]:
arr2

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 11],
       [ 7,  8,  9, 12]])

In [169]:
arr2[:][1]

array([ 4,  5,  6, 11])

In [171]:
arr2[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

Vectors

Arithmatice Operatons On Array

In [186]:
arr1=np.array([1,2,3])

In [173]:
arr2=np.array([4,5,6])

In [174]:
arr1 + arr2

array([5, 7, 9])

In [175]:
arr1 - arr2

array([-3, -3, -3])

In [176]:
arr1 * arr2

array([ 4, 10, 18])

In [177]:
arr1 / arr2

array([0.25, 0.4 , 0.5 ])

In [179]:
np.exp(arr1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [180]:
np.sqrt(arr2)

array([2.        , 2.23606798, 2.44948974])

In [181]:
np.setdiff1d(arr1,arr2)

array([1, 2, 3])

In [182]:
np.sin(arr1)

array([0.84147098, 0.90929743, 0.14112001])

In [183]:
np.cos(arr2)

array([-0.65364362,  0.28366219,  0.96017029])

In [184]:
np.log(arr1)

array([0.        , 0.69314718, 1.09861229])

In [185]:
np.min(arr1)

1